= Hope Evangelical Lutheran Church Missouri Synod

In the name of the Father, and of the Son, and of the Holy Spirit, Amen.

== Preamble

Recognizing our unity in Christ and our common practice in the Christian faith; desiring to express our fellowship in worship and work; knowing our spiritual needs; mindful of our Christian privileges and duties, and wishing to observe orderly cooperation, we adopt the following constitution:

== ARTICLE I - NAME AND INCORPORATION

The name of the congregation shall be Hope Evangelical Lutheran Church. The congregation shall be incorporated under the laws of the state of Ohio.

== ARTICLE II - CONFESSION OF FAITH

The congregation accepts all the canonical books of the Old and New Testaments as a whole and in all their parts as the divinely inspired, revealed, and inerrant Word of God and submits to this as the only infallible authority in all matters of faith and life. As brief and true statements of the doctrines of the Word of God, the congregation accepts and confesses the following Symbols, subscription to which shall be required of all its members: (1) the ancient ecumenical Creeds the Apostolic, the Nicene, and the Athanasian; (2) the Unaltered Augsburg Confession and Luther's Small Catechism. As further elaboration of and in accord with these Lutheran Symbols, the congregation also receives the other documents in the Book of Concord of 1580: the Apology, Luther's Large Catechism, the Smalcald Articles and the Formula of Concord; and recognizes them as normative for its theology. The congregation accepts without reservation the symbolical books of the evangelical Lutheran Church, not insofar as, but because they are the presentation and explanation of the pure doctrine of the Word of God and a summary of the faith of the evangelical Lutheran Church.

== ARTICLE III - PURPOSE

The purpose of the congregation shall be to proclaim and propagate the Christian faith through the Means of Grace.

== ARTICLE IV - POWERS

. All power in the congregation has its source in the Word of God, which is the norm for its faith and life. All individuals and groups within the congregation shall submit to the authority of the Word; and the life and activity of the congregation and its organizations shall conform to it.
. In all matters left undecided in Holy Writ and not subject to civil laws, the congregation itself, in accordance with this constitution, and not any individual or group within it, or synod, shall have the right of ultimate decision.
. The powers of the congregation shall be vested in the congregation meeting called and conducted in such manner as is provided in this constitution, and, to the extent conveyed by this constitution or as assigned from time to time by the congregation meeting, in the boards elected by the congregation.
. All schools, societies, groups and organizations within the church and identified with our congregation must be organized with the consent of the majority of members present at a legally called congregation meeting and labor under the guidance of church council, also empowered by the congregation.
. In fulfillment of its purposes the congregation is empowered to:
.. acquire real and personal property by gifts, devise, bequest, purchase, or other lawful means;
.. hold title to and use its property for any and all activities consistent with its purpose;
.. sell, mortgage, lease, transfer, or otherwise dispose of its property by any lawful means;
.. enter into contract;
.. sue and be sued;
.. elect officers and boards for the exercise of their powers and authority and require the to conduct their affairs in accordance with this constitution and its bylaws, and the resolutions of the congregation.
. Real property shall not be purchased, disposed of, or encumbered in any manner except by resolution adopted by not less than a two-thirds majority ballot vote of the members present and voting at a legally called meeting of the congregation.
. Should the congregation cease to do business and be dissolved, all property and funds remaining after the payment of the debts of the congregation shall be distributed to a corporation trust, foundation, or other organization organized and existing for religious and/or charitable purposes which would then qualify under the provisions of section 501 (e) (3) of the Internal Revenue Code, as now enacted or as may hereafter be amended.

== ARTICLE V - MEMBERSHIP IN THE CONGREGATION

. Members of the congregation shall be those who are designated as such at the time that this constitution is adopted, and those who are admitted thereafter; and who maintain their membership in accordance with the provisions of this constitution and its bylaws. There shall be no membership restrictions with respect to race, color, national origin or sex.
. Members shall be classified as (a) baptized; (b) communicant, but unconfirmed; (c) confirmed; (d) voting.
.. Baptized members are those persons who have been received by the Sacrament of Holy Baptism in this congregation, or having been previously baptized in the mane of the Triune God, have been received by proper transfer from other congregations or by affirmation of faith.
.. Communicant, but unconfirmed members are those who have received training in the meaning and practice of the Lord's Supper and who participate in Communion but who have not yet been confirmed.
.. Confirmed members are baptized persons who have been confirmed in this congregation, those who have been received by adult Baptism, or by transfer as confirmed members from other congregation, or baptized persons received by affirmation of faith.
.. Voting members shall be those who are confirmed members in good standing, as provided by the bylaws.
. It shall be the privilege and duty of members of this congregation to:
.. make diligent use of the Means of Grace, both Word and Sacraments;
.. life a Christian life in accordance with the Word of God and the teachings of the Lutheran Church;
.. support the work of the congregation.

== ARTICLE VI - DISCIPLINE

. A member who advocates doctrines which are contrary to the Holy Scripture and the Confessions of the Church, or who is guilty of conduct that is grossly unbecoming a member of the Body of Christ, shall be subject to discipline.
. Discipline shall be administered by the church council on behalf of the congregation, in consultation with the board of elders as indicated in the bylaws. Following the church council's action, the individual has the right of appeal to the congregation.
. Discipline in the congregation shall be exercised in accordance with Matthew 18:15-18.

== ARTICLE VII - WORSHIP

As an expression of the unity of the church in Christ the congregation recognizes the desirability of conforming to the practices of other Lutheran congregations.

== ARTICLE VIII - THE PASTOR

. A pastor of the congregation shall be a person whose soundness in the faith, aptness to teach, and educational qualifications have been examined and approved by the Church, and who has been properly ordained; who accepts and adheres to the Confession of Faith of the congregation; and who strives in life and conduct to be above reproach.
. Authority to call a pastor shall rest in the congregation. Such authority to call shall be exercised by not less than a two-thirds majority ballot vote of members present and voting at the meeting legally called for that purpose.
. In the event of a vacancy in the pastoral office, the Church Council shall provide for interim pastoral service.
. If in the judgment of the congregation the pastor is no longer able to serve it satisfactorily, the pastor may be requested to resign. Before the resignation is requested, all parties, including the pastor, shall have the opportunity of being heard at a specially called meeting of the Church Council. After the hearing before the Church Council a special meeting of the congregation may be called to consider a request for the pastor's resignation. A resolution requesting a pastor's resignation must be adopted by a two-thirds majority ballot vote of those present and voting. Not less than ten days notice of such meeting of a congregation must be given. If the pastor's resignation has been requested in the manner here provided, the pastor shall vacate the office at the time the congregation specifies. Should the pastor fail to do so the Church Council shall declare the pastoral office vacant.
. In the event of alleged defection in doctrine or alleged conduct unbecoming a pastor, the matter shall be handled by the Church Council or a committee appointed thereby.

== ARTICLE IX - MEETINGS OF THE CONGREGATION

. The power and authority of the congregation shall be exercised through the congregational meeting, which shall be called and conducted in conformity with civil laws and the provisions of the constitution and bylaws of the congregation.
. The semi-annual meetings of the congregation shall be held in January and in July. Notice of the meeting shall be given as provided in the bylaws.
. A quorum for any regular or special meeting of the congregation shall be 5% of the voting members.
. A special meeting of the congregation may be called by action of the congregation, by petition of at least ten (10) of the voting members, or by any one of the following: the Church Council, the president of the congregation, or the pastor. Official notice of a special meeting of the congregation shall be in writing and shall be posted conspicuously in the place where the congregation customarily worships. Such notice shall state the time, the place and the purpose of the meeting. It shall be signed by the president and the secretary of the congregation, or by the person or persons who have called the meeting, as authorized by this paragraph. The notice of a special meeting shall also be read at all public services of the congregation held during the tend days preceding the date of the meeting.
. The pastor and president of the Church Council shall be notified of the time and place at which a special meeting of the congregation is to be held.
. Only the business for which a special meeting has been called shall be transacted at the meeting.

== ARTICLE X - OFFICERS, COMMITTEES AND ELDERS

At a special meeting held in May, the congregation shall elect individuals to fill open positions of the Church Council and Board of Elders for the next term beginning the first Sunday of July as follows:

. Vice-President who serves in this capacity for one year and assumes the presidency the following year. During the year of serving as Vice-President, this person may also serve in another council position.
. Secretary for a two year term and is elected in even years.
. Treasurer for a two year term and is elected in odd years.
. and the chairs of the following committees for a one year term. The council may decide to combine one or more committees for a particular term. If so, there would be one chairperson for that combined committee with one vote on the council:
.. Elders
.. Outreach/Mission
.. Worship
.. Education
.. Stewardship
.. Property
.. Fellowship
. Elders for two year terms. The number to serve as elder will vary with the size of the congregation as indicated in the bylaws.

No person shall be eligible to serve in the same capacity on the Church Council for more than four (4) successive terms. The duties of the officers and elders of the congregation shall be those provided in the bylaws. The officers of the congregation and the chairs of the committees together with the pastor shall constitute the Church Council. The president, the vice-president, and secretary of the congregation shall serve in those same as president, vice-president, and secretary of the Church Council respectively.

== ARTICLE XI - BYLAWS

. The congregation shall adopt such bylaws as may from time to time be necessary. No bylaw may conflict with this constitution.
. Bylaws may be adopted or amended at any legally called and conducted meeting of the congregation by a two-thirds majority vote of those present and voting.

== ARTICLE XII - AMENDMENTS

. The doctrinal basis and the confessional subscription contained in xref:ARTICLE II - CONFESSION OF FAITH[Article II], and this paragraph of xref:ARTICLE XII - AMENDMENTS[Article XII] shall be unalterable; and no amendment to this constitution shall conflict therewith.
. A proposed amendment to this constitution shall be:
.. read at a public service of the congregation or mailed to the voting members not less than thirty days before the legally called meeting at which it is to be considered;
.. approved without change at the legally called meeting following its announcement, by a majority vote of those present and voting;
.. ratified without further change at the next semi-annual meeting by a two-thirds vote of those present and voting.
. If a proposed amendment fails of adoption, it may be amended by a majority vote of those present and voting, and adopted without change by a two-thirds majority of those present and voting at the next semi-annual meeting.
. At least once every five (5) years the council shall appoint a constitutional committee consisting of a chairman and four members to review the constitution in consultation with the synod. Any changes felt necessary by the committee are to be brought before the congregation at the next semi-annual meeting.
. At least once every five (5) years the council shall appoint a constitution committee consisting of a chairman and four members to review the constitution in consultation with the synod. Any changes felt necessary by the committee are to be brought before the congregation at the next semi-annual meeting for action as outlined above.

= BYLAWS

== PART I - COMMUNION PARTICIPATION
(Cf. xref:ARTICLE II - CONFESSION OF FAITH[Article II of the Constitution])

. This congregation invites all of its members who have been prepared to receive the Sacrament to participate regularly in Holy Communion
. Preparation for Holy Communion will normally be provided for persons as young as ten years of age.
. Participation in Holy Communion shall be open to members of other congregations who accept the Lutheran teaching in regard to this Sacrament.
. It shall be made known to prospective participants that the belief of this congregation is: Participation in the Lord's Supper is the reception of "the body and blood of our Lord Jesus Christ given with bread and wine, instituted by Christ himself for us to eat and drink."* We hold that a "person is well prepared and worthy who believes these words, given and shed for you for the remission of sins. But anyone who does not believe these words, or doubts them, is neither prepared nor worthy, for the words for you require simply a believing heart"* +
*From _The Small Catechism in Contemporary English,_ +
(C) 1968 Augsburg Publishing House and Fortress Press.
. Record of participation in Holy Communion shall be maintained. If a member of another congregation communes, notice shall be sent to the pastor of that congregation.

== PART II - CONFLICTING LOYALTIES
(Cf. xref:ARTICLE II - CONFESSION OF FAITH[Article II of the Constitution])

. While the buildings of the congregation shall be open to all people to share in its worship, instruction, pastoral care, and fellowship, the congregation rejects all fellowship with organizations which are avowedly religious and which practice forms of religion without confessing faith in the Triune God and in Jesus Christ as the eternal Son of God incarnate to be our only Savior from sin, and which thus teach salvation by works.
. Ceremonies of such organizations indicated above shall not be permitted in the buildings or premises of the congregation.

== PART III - MEMBERSHIP
(Cf. xref:ARTICLE V - MEMBERSHIP IN THE CONGREGATION[Article V of the Constitution])

. Baptized Members
.. A child, one or both of whose parents or guardians are members of the congregation shall, upon receiving Baptism, become a baptized member.
.. A child, neither of whose parents or guardians is a member of this congregation, shall upon receiving Baptism, become a baptized member of this congregation, unless for good reason the child is to be a baptized member of another congregation, in which case membership shall be transferred to that congregation.
.. A child baptized in another congregation shall be received as a baptized member in the congregation when a transfer has been received.
.. An unbaptized adult who has received instruction and has given evidence of an adequate understanding and acceptance of the teachings of the Word of God as confessed by the Lutheran Church, shall, upon confession of faith and Baptism, become a baptized member of the congregation.
.. When one or both parents of baptized children are received into the membership of the congregation such children should be received as baptized members with the consent of the member parents or parents.
.. When the parents of a baptized child are not themselves members of the Lutheran Church but move into the area served by this congregation and desire to have their child put within the pastoral care of this congregation, the child may be received as a baptized member.
. Confirmed Members
.. A baptized adult, not previously a confirmed member of a Lutheran congregation, shall become a confirmed member of this congregation after having received instruction, having given evidence of adequate understanding of the teachings of the Word of God as confessed by the Lutheran Church, and having publicly affirmed his faith.
.. A baptized member of the congregation shall become a confirmed member through the rite of confirmation, except that an adult who has become a baptized member in accordance with the provisions of section A, 4 of this part of the bylaws shall be considered a confirmed member without participation in the rite of confirmation.
.. An applicant for membership who presents a Letter of Transfer which certifies that the applicant is a confirmed member in good standing of a Lutheran congregation shall become a confirmed member of the congregation upon the approval of the Church Council. The acceptance of the applicant shall be reported to the congregation.
.. An applicant for membership who presents evidence of confirmation in a Lutheran congregation but does not have a Letter of Transfer shall be admitted to confirmed membership when the Church Council has determined that the applicant meets the standards of Christian faith and life indicated in the constitution and bylaws and has reaffirmed that faith before the congregation.
. Voting Members +
The register of voting member shall be available at all regularly called meetings of the congregation and shall consist of:
.. those who are confirmed member and have reached the age of 16;* and
.. those who partake of Holy Communion, and
.. those who participate in the life and worship of the congregation. +
+
*Except where it becomes necessary to conform to state law and the legal age of 18.
. Pastoral Care of Membership
.. The congregation shall, in the event of the removal of a member from the community it serves, encourage the member to request transfer to a Lutheran congregation which can serve him or her effectively. Should the member fail to request a transfer, a Lutheran congregation in the community of his residence shall be notified.
.. A confirmed member in good standing desiring to change his membership to another congregation shall, upon request, receive a Letter of Transfer.
.. A confirmed member who does not, for a period of 6 months, partake of Holy Communion, and does not appear to desire to participate in the life and worship of the congregation shall be contacted by the pastor or the congregation's officers and encouraged by them to active membership. If, during the next 6 months the confirmed member does not actively participate, that member's name shall be removed from the membership roster of the congregation but be retained on a responsibility list as one who is in special need of the congregation's prayer and concern and be so notified.
.. A person removed from the membership roster by the preceding action of the bylaws and who desires reinstatement shall make written request to council. Council shall submit such requests to the congregation at the next semi-annual meeting for action. If approved, said person shall be eligible to vote at the following semi-annual congregation meeting and be restored to all rights and privileges of active membership.
.. A child, neither of whose parents of guardians is a member of the congregation, may be removed from the roster of baptized member if that child fails to participate in the life and worship of the congregation.
. Discipline (Cf. xref:ARTICLE VI - DISCIPLINE[Article VI of the Constitution])
In exercising discipline as provided in the constitution, the following shall be the procedure:
.. The board of elders will be concerned with discipline in the church. Should they become aware of a need for discipline, a member of the elders shall speak with the individual involved with the hope for reconciliation and, if needed, repentance. If the discipline concern remains, the board of elders will seek to have a meeting together with the individual. If the individual will not cooperate in such a meeting, the board of elders will send a registered letter with the reason for the meeting stated and a specific date and time given for the meeting. If after meeting with the individual (or if it has been established that the individual will not cooperate by meeting as described above) the elders unanimously feel that discipline is to be taken, they will make their recommendation to the Church Council.
.. A person who is requested to appear before the Church Council for possible discipline, shall be advised in writing no less than ten days prior to the hearing. The written notice shall include the time and place of the hearing and shall specify the exact reason for the possible discipline. If that person fails to appear at the time and place without valid excuse, the Church Council may proceed with the hearing and may reach its conclusion in the absence of that person.
.. Should the person be found guilty by a two-thirds vote of the members of the Church Council, the Council shall impose suspension from membership and denial of the Sacraments until proof is given of sufficient repentance. The action of the Church Council shall be in writing and delivered by registered letter. The individual's right to appeal to the congregational voters meeting will be described in the same registered mailing. The right to appeal will expire, and the discipline take affect, 30 days after the receipt of the registered mailing.

== PART IV - THE PASTOR
(Cf. xref:ARTICLE VIII - THE PASTOR[Article VIII of the Constitution])

. When the congregation has voted to call a pastor, it shall issue a Letter of Call to the pastor-elect. It shall be signed by the chairman and the secretary of the meeting at which the Call was voted. A Call to a member of the clergy to be an assistant pastor shall be issued only with the concurrence of the pastor of the congregation and in accordance with the provisions of this paragraph.
. The call shall normally be for an indefinite time. A call issued to an assistant pastor may be for a definite.
. If a pastor receives a Call to another ministry, the pastor shall consult the Church Council, or, if desired, the congregation, before reaching a decision. The pastor shall announce a decision as quickly a as possible, normally within three weeks. When a Call has been accepted, the pastor's ministry in this congregation shall be terminated as soon as possible, normally within a month.

== PART V - MEETINGS OF THE CONGREGATION
(Cf. xref:ARTICLE IX - MEETINGS OF THE CONGREGATION[Article IX of the Constitution])

. Announcement of the time and place of the semi-annual meetings of the congregation shall be made at two public services immediately preceding the meeting, said services to be at least a week apart, and in such publications as the congregation or the pastor may periodically issue, or by written notice to the voting members mailed not less than ten days in advance of the meeting.
. The current rosters of voting, confirmed, and baptized members shall be available at each meeting to the congregation.
. The semi-annual meetings shall receive reports from all the committees of the congregation. Such reports, including a financial statement, shall be submitted in writing to the pastor not less than ten days before the meeting.
. Elections shall be held in accordance with xref:ARTICLE X - OFFICERS, COMMITTEES AND ELDERS[Article X] of this Constitution.
. Unless otherwise ordered, parliamentary procedures shall be in accordance with Robert's Rules of Order.

== PART VI - OFFICERS, COMMITTEES AND ELDERS
(Cf. xref:ARTICLE X - OFFICERS, COMMITTEES AND ELDERS[Article X of the Constitution])

. ELIGIBILITY AND DUTIES OF MEMBERS OF CHURCH COUNCIL
.. Only a voting member of the congregation, 18 years of age or over shall be eligible to serve on the Church Council.
.. The president shall preside at meetings of the Church Council and the congregation.
.. The vice-president shall preside at meetings of the Church Council and the congregation in the absence of the president.
.. The secretary shall keep the minutes of the Church Council and of the congregation and have custody of the archives of the congregation.
.. The treasurer shall be responsible for all funds of the congregation and oversee the receipt and disbursement of funds in accordance with the decisions of the congregation and the Church Council. All appointments, and/or services used, to support the treasurer must be approved by Church Council.
. MEMBERSHIP AND MEETINGS OF THE COMMITTEES
.. The committees shall consist of a chairperson and the members recruited by that chairperson. Members shall be approved by the Council for a one year term.
.. If a vacancy occurs on a committee, the chairperson together with Church Council will decide if it needs to be filed and if so shall strive to fill the position.
. DUTIES AND RESPONSIBILITIES OF THE COMMITTEES
.. Each committee shall report on its activities as the semi-annual meetings of the congregation and at such other times as the congregation may decide.
... Outreach/Mission Committee
.... shall be involved in caring for the physical and spiritual needs of those outside the congregation
.... shall be involved in a regular schedule of visitations to prospective members
.... shall be concerned with the work of the church throughout the world
... Worship Committee
.... shall be concerned with the orderly conduct of the worship service. The committee shall be responsible for: ushers, acolytes, greeters, nursery, music and choir robes, altar and vestments, flowers, hymnals, bulletins, communion, seasonal celebrations - Lent, Palm Sunday, Easter, Pentecost, Reformation, Advent, Christmas and all other days of celebration in the church year.
... Education Committee
.... shall set up and supervise the Sunday School (teachers, materials, teaching aids, and programs
.... shall conduct a Bible school during a summer vacation
.... shall plan for adult education
.... shall provide for catechism instruction
... Stewardship Committee
.... shall elect a financial secretary
.... shall encourage a stewardship education
.... shall be responsible for the audit of financial records
... Property Committee
.... shall maintain the church building and its premises
... Fellowship Committee
.... shall be responsible for the fellowship of the congregation
.... shall plan for social gatherings throughout the year
.... shall represent auxiliary and social groups within the congregation
. MEETINGS OF THE CHURCH COUNCIL +
+
In addition to the provisions of the constitution, the following shall govern the Church Council in the conduct of its meetings
.. A quorum of any regular or special meeting shall be one-half of the membership.
.. A member of the Church Council who is absent for two consecutive regular meetings shall be consulted by the president of the congregation; if a member is absent from three consecutive regular meetings without valid excuse, the Church Council may declare the office vacant.
.. In the event of a vacancy in Church Council, the remaining council members will determine at their next meeting if the vacancy needs to be filled or if the duties of that person can be incorporated with the duties of another council member. If it is necessary to fill the position a temporary replacement will be appointed by Church Council. This appointment will be ratified by a special congregational voters meeting. The congregation will have at least 3 weeks notice before this meeting and may nominate other individuals up until one week before the meeting. No additional nominations will be considered one week before the voters meeting.
.. A special meeting may be called by the pastor, the president, or any three members of the Church Council. Notice of such meeting shall be given not less than five days prior to the meeting and announced at a public service if one is held during that period.
. DUTIES AND RESPONSIBILITIES OF THE CHURCH COUNCIL
.. Have general oversight of the life and work of the congregation and coordinate the activities of the committees of the congregation;
.. Determine rosters of the baptized, the confirmed, and the voting members of the congregation;
.. Perform such other duties and responsibilities as delegated by the congregation;
.. Conduct regular meetings not less than once each month at such time and place as the Church Council may determine;
.. Secure necessary staff other than pastor(s), such as administrative assistant, Christian day school teacher, business administrator, church musician, parish education director, parish secretary, parish worker or youth worker, intern, custodian, etc. and fix and review annually their salaries;
.. Review annually the salary of the pastor(s) and make adjustments from time to time within limits of the budget approved by the congregation;
.. Prepare the budget and submit it to the congregation at the semi-annual meeting in July, with its recommendations;
.. Administer discipline in accordance with the provisions of this constitution and its bylaws;
.. Report its activities at the semi-annual meeting for the congregation and at such other times as the congregation may decide.
.. Have authority between meetings for the congregation to choose delegates to any group or meeting in which the congregation is entitled to representation.
.. Provide approval for non-budgeted expenditures in the amount up to 10 percent of the total approved congregational budget. Non-budgeted expenditure approvals cannot exceed 10 percent in any one-budget year without the approval of the congregation. Non-budgeted expenditures exceeding 10 percent of the approved budget for the current budget year shall be brought before the congregation for approval. This shall not include gifts received for a specific purpose.
.. Provide an annual audit of the church's financial records.
. NOMINATION AND ELECTION PROCESS FOR MEMBERS OF CHURCH COUNCIL +
+
The Board of Elders will serve as the nominating committee. At a time at least 8 weeks before the May voters meeting, the nominating committee will make known to the congregation the offices which need to be filled. Members of the congregation will make their nominees, and/or their personal desire to serve, known to the nomination committee. Unless reasons of church discipline prohibit it, the nominating committee will speak with those nominated about the positions and whether they will accept the nomination. The nominating committee will also meet to consider who they would like to nominate for offices and speak with those individuals. The results of the nominating committee will be published at least 2 weeks before the voters meeting. No additional nominations will be considered one week before the voters meeting.
. ELIGIBILITY, SIZE, AND MEETINGS OF THE BOARD OF ELDERS +
+
While either men or women may serve on this board, there are certain duties limited to men (defined in section H) due to how they pertain to the public office of the pastoral ministry. +
+
The nature of the duties of an elder requires that only those noted for their Christian knowledge, zeal, and experience in the spiritual work of Christ shall be elected. To be eligible to be an elder, someone must have served at least one full term on our Church Council and currently be regular in attendance at worship services and a Bible class. +
+
The Board of Elders will all be elected by the congregation and will each serve two year terms. The size of the Board of Elders will reflect the size of the congregation with one elder for up to or a fraction of every 80 baptized members of the congregation roster with a minimum of 3 elders. +
+
A person may serve on the Board of Elders for as many terms as they are elected and desire to serve. However, they can serve as the elder's representative to the Church Council only two consecutive years. +
+
When a vacancy occurs in the Board of Elders, the Church Council will serve as the nomination committee to fill the vacancy. A special voters meeting will elect an elder to serve the completion of the term. There will be at least 3 weeks notice given before this special voters meeting. Nominations may be given to the president of the Church Council up to one week before the special voters meeting. +
+
No additional nominations will be considered one week before the voters meeting. +
+
The elders will meet independent of the Church Council and will annually designate their chair who will serve as a council member. It is possible for an elder to simultaneously hold another position on the Church Council.
. DUTIES AND FUNCTIONS OF THE BOARD OF ELDERS +
+
The Board of Elders does not make final decisions, but will give recommendations and counsel to the Pastor, Church Council, and congregation. The elders shall:
.. Encourage and assist the Pastor in his work by word and action. Such assistance would I include prayer for the Pastor, distribution assistance for the Lord's Supper, assisting the Pastor in counseling with difficult cases and in finding peaceful and God pleasing solutions to personal problems within the congregation, and planning with the Pastor, and appropriate committees, items to assist the spiritual health of the congregation.
.. Care for families as assigned them in liaison with the Pastor and Church Council. This care would include prayer for the families, contact when they have missed worship for several weeks, visits when in the hospital, support in times of crisis, whatever kind of visitation may be helpful. Individuals will also be encouraged to initiate contact with an elder if they have a concern, physical need, or spiritual need.

+
In keeping with teachings of the Lutheran Church Missouri Synod, the pastoral office is Scripturally narrowed to men. Therefore, only a man would be allowed to deliver a sermon or lead the worship service. It is also our intent to heed the strong recommendation of the Synod's Commission on Theology and Church Relations when it states: +
"While some might argue that assisting the presiding minister in the distribution of the elements is not necessarily a distinctive function of the pastoral office, the commission strongly recommends that, to avoid confusion regarding the office of the public ministry and to avoid giving offense to the church, such assistance be limited to men" (_Women in the Church,_ Commission on Theology and Church Relations, Lutheran Church Missouri Synod, September 1985, page 47)
. NOMINATIONS AND ELECTION PROCESS FOR BOARD OF ELDERS +
+ 
When elders are to be elected, the Church Council will serve as the nominating committee for the nomination of elders. At a time at least 8 weeks before the May voters meeting, the nominating committee will make known to the congregation the positions which need to be filled. Members of the congregation will make their nominees, and/or their personal desire to serve, known to the nominating committee. Unless the person does not fit the criteria for an elder described above, the nominating committee will speak with the nominee about the position and whether the individual will accept the nomination. The nominating committee will also meet to consider who they would like to nominate for elder and speak with those individuals. The results of the nominating committee will be published at least 2 weeks before the voters meeting. No additional nominations will be considered one week before the voters meeting.

== PART VII - PARISH RECORDS

The records of the congregation shall be and remain the property of the congregation. The pastor shall be responsible for the maintenance of the records, except as otherwise provided herein. Upon the termination of a pastor's service to the congregation, the records shall have been brought up to date prior to departure. The records will consist of

. the roster of baptized, confirmed, and voting members;
. the ministerial acts performed by the pastor;
. the minutes of the meetings of the congregation and the Church Council, for which the secretary of the congregation shall be responsible;
. the financial records of the congregation; for which the treasurer of the congregation shall be responsible.
